#!/usr/bin/env nextflow

/*
 * ChampHLA frozen production caller workflow.
 *
 * This workflow intentionally runs callers only. Pair-level plurality and all
 * comparisons are generated by the truth-free Python layer after native output
 * validation. No process is optional and no modality silently drops a caller.
 */

nextflow.enable.dsl = 2

include { OPTITYPE_FASTQ } from './modules/optitype'
include { ARCASHLA_FASTQ } from './modules/arcashla'
include { SPECHLA as SPECHLA_BAM } from './modules/spechla'
include { HLAHD as HLAHD_BAM; HLAHD_FASTQ } from './modules/hlahd'
include { POLYSOLVER } from './modules/polysolver'
include { KOURAMI } from './modules/kourami'
include { T1K_FASTQ } from './modules/t1k'
include { CRAM_TO_BAM; BAM_TO_FASTQ; EXTRACT_HLA_AND_CONVERT } from './modules/bam_to_fastq'

def fail(message) {
    log.error "ERROR: ${message}"
    System.exit(1)
}

if (!params.input_samplesheet) fail('--input_samplesheet is required')
if (!params.input_type) fail('--input_type is required')
if (!params.run_modality) fail('--run_modality is required')
if (!params.tools) fail('--tools is required')
if (!params.hlahd_db) fail('--hlahd_db is required')
if (!params.t1k_hlaidx) fail('--t1k_hlaidx is required')

def modality = params.run_modality.toString().toLowerCase()
def tools = params.tools.tokenize(',')*.trim()*.toLowerCase()
def expectedPanels = [
    wgs: ['spechla', 'hlahd', 'optitype', 'kourami', 't1k'],
    wes: ['hlahd', 'optitype', 'polysolver', 'spechla', 't1k'],
    rnaseq: ['arcashla', 'hlahd', 'optitype', 't1k'],
]
if (!expectedPanels.containsKey(modality)) fail("unsupported modality: ${modality}")
if (tools.size() != tools.toSet().size()) fail('duplicate caller in --tools')
if (tools.toSet() != expectedPanels[modality].toSet()) {
    fail("${modality} requires exactly: ${expectedPanels[modality].join(',')}")
}
if (modality == 'rnaseq' && params.input_type != 'fastq') {
    fail('RNA-seq requires a paired FASTQ samplesheet')
}
if (modality == 'wes' && params.input_type == 'fastq') {
    fail('WES FASTQ cannot execute the frozen POLYSOLVER panel; supply a GRCh38DH BAM/CRAM')
}
if (modality == 'wgs' && params.input_type != 'bam') {
    fail('WGS caller input must be the staged mate-aware HLA BAM')
}
if (params.input_type == 'cram' && !params.reference_fasta) {
    fail('CRAM decoding requires --reference_fasta')
}

workflow {
    def ch_bam = Channel.empty()
    def ch_fastq = Channel.empty()
    def header = file(params.input_samplesheet).text.readLines()[0]?.toLowerCase() ?: ''

    if (params.input_type == 'fastq') {
        if (!header.contains('fastq_1') || !header.contains('fastq_2')) {
            fail('FASTQ samplesheet must contain fastq_1 and fastq_2')
        }
        ch_fastq = Channel.fromPath(params.input_samplesheet, checkIfExists: true)
            .splitCsv(header: true)
            .map { row -> tuple(row.sample_id, file(row.fastq_1), file(row.fastq_2)) }
    } else if (params.input_type in ['bam', 'cram']) {
        def requiredColumn = params.input_type == 'cram' ? 'cram_path' : 'bam_path'
        if (!header.contains(requiredColumn)) fail("samplesheet must contain ${requiredColumn}")
        ch_bam = Channel.fromPath(params.input_samplesheet, checkIfExists: true)
            .splitCsv(header: true)
            .map { row -> tuple(row.sample_id, file(row[requiredColumn])) }
        if (params.input_type == 'cram') {
            def ch_ref = Channel.fromPath(params.reference_fasta, checkIfExists: true).first()
            CRAM_TO_BAM(ch_bam, ch_ref)
            ch_bam = CRAM_TO_BAM.out.bam
        }
    } else {
        fail("unsupported input type: ${params.input_type}")
    }

    if (modality == 'rnaseq') {
        ARCASHLA_FASTQ(ch_fastq)
        HLAHD_FASTQ(ch_fastq, params.hlahd_genes)
        OPTITYPE_FASTQ(ch_fastq, 'rna')
        T1K_FASTQ(ch_fastq)
    } else {
        SPECHLA_BAM(ch_bam, params.reference_build)
        if (modality == 'wgs') {
            HLAHD_BAM(ch_bam, params.reference_build, params.hlahd_genes)
            KOURAMI(ch_bam)
            BAM_TO_FASTQ(ch_bam)
            OPTITYPE_FASTQ(BAM_TO_FASTQ.out.reads, 'dna')
            T1K_FASTQ(BAM_TO_FASTQ.out.reads)
        } else {
            POLYSOLVER(ch_bam)
            EXTRACT_HLA_AND_CONVERT(ch_bam)
            HLAHD_FASTQ(EXTRACT_HLA_AND_CONVERT.out.reads, params.hlahd_genes)
            OPTITYPE_FASTQ(EXTRACT_HLA_AND_CONVERT.out.reads, 'dna')
            T1K_FASTQ(EXTRACT_HLA_AND_CONVERT.out.reads)
        }
    }
}

workflow.onComplete {
    if (!workflow.success) fail('one or more required caller processes failed')
    log.info "ChampHLA caller workflow completed: ${modality}"
}
