#!/bin/bash
#SBATCH --job-name=pihla_rna_arr
#SBATCH --account=project_2008084
#SBATCH --partition=small
#SBATCH --time=12:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --output=/scratch/project_2008084/pihla-publish/analysis/logs/rna_arr_%A_%a.out
#SBATCH --error=/scratch/project_2008084/pihla-publish/analysis/logs/rna_arr_%A_%a.err

# RNA batch array task — each array task processes one batch file of samples.
# Batch files are pre-generated by the submission script.
#
# Usage (do not call directly — use submit_rna_6trimodal.sh or submit_rna_missing24.sh):
#   sbatch --array=0-N[%1] slurm_rna_array.sh <batch_dir>
#
# Each batch_<N>.txt in batch_dir must contain one sample ID per line.
# Searches sample_fastq_urls.tsv first, then batch5 as fallback.

set -euo pipefail

BATCH_DIR="${1:?ERROR: batch_dir argument required}"
BATCH_FILE="$BATCH_DIR/batch_${SLURM_ARRAY_TASK_ID}.txt"

[[ -f "$BATCH_FILE" ]] || { echo "ERROR: $BATCH_FILE not found" >&2; exit 1; }

mapfile -t samples < "$BATCH_FILE"
echo "[$(date)] Array task ${SLURM_ARRAY_TASK_ID}: ${#samples[@]} samples: ${samples[*]}"

INDEX=/scratch/project_2008084/hla_calibration/rna/index/sample_fastq_urls.tsv
INDEX_B5=/scratch/project_2008084/hla_calibration/rna/index/sample_fastq_urls_batch5.tsv
FASTQ_ROOT=/scratch/project_2008084/hla_calibration/rna/fastqs
BATCH_ROOT=/scratch/project_2008084/hla_calibration/rna_batches
WORK_ROOT=/scratch/project_2008084/hla_calibration/work
PIPELINE_DIR=/scratch/project_2008084/pihla-publish

mkdir -p "$FASTQ_ROOT" /scratch/project_2008084/hla_calibration/logs
module load python-data 2>/dev/null || true

# ── Step 1: Download FASTQs ───────────────────────────────────────────────
echo "[$(date)] Step 1: downloading FASTQs"
for sample in "${samples[@]}"; do
    r1="$FASTQ_ROOT/${sample}_R1.fastq.gz"
    r2="$FASTQ_ROOT/${sample}_R2.fastq.gz"
    [[ -f "$r1" && -f "$r2" ]] && echo "  SKIP $sample (FASTQs exist)" && continue

    line=$(grep "^${sample}"$'\t' "$INDEX" 2>/dev/null | head -1 || true)
    if [[ -z "$line" && -f "$INDEX_B5" ]]; then
        line=$(grep "^${sample}"$'\t' "$INDEX_B5" 2>/dev/null | head -1 || true)
    fi
    [[ -z "$line" ]] && echo "  SKIP $sample: not in index" && continue

    url_r1=$(echo "$line" | cut -f2)
    url_r2=$(echo "$line" | cut -f3)

    echo "  Downloading $sample R1..."
    wget -q -O "$r1" "$url_r1" || curl -s -o "$r1" "$url_r1"
    echo "  Downloading $sample R2..."
    wget -q -O "$r2" "$url_r2" || curl -s -o "$r2" "$url_r2"
    echo "  Downloaded $sample"
done
echo "[$(date)] Downloads complete"

# ── Step 2: Submit pipeline jobs ──────────────────────────────────────────
echo "[$(date)] Step 2: submitting pipeline jobs"
job_id_list=""
for sample in "${samples[@]}"; do
    r1="$FASTQ_ROOT/${sample}_R1.fastq.gz"
    [[ ! -f "$r1" ]] && echo "  SKIP $sample: no FASTQ" && continue

    if [[ -d "$BATCH_ROOT/$sample/results" ]]; then
        n_done=$(find "$BATCH_ROOT/$sample/results" -name "*_arcashla.txt" 2>/dev/null | wc -l)
    else
        n_done=0
    fi

    job_id=$(sbatch --parsable \
        "$PIPELINE_DIR/slurm_rna_sample.sh" \
        "$sample" "$FASTQ_ROOT" "$BATCH_ROOT" "$WORK_ROOT")
    job_id_list="${job_id_list} ${job_id}"
    echo "  Submitted $sample → job $job_id"
done

# ── Step 3: Wait for pipeline jobs ────────────────────────────────────────
if [[ -n "${job_id_list}" ]]; then
    ids=$(echo "$job_id_list" | tr ' ' ',' | sed 's/^,//')
    echo "[$(date)] Step 3: waiting for jobs ($ids)"
    while squeue --jobs="$ids" -h 2>/dev/null | grep -q .; do
        sleep 60
    done
    echo "[$(date)] All pipeline jobs finished"
fi

# ── Step 4: Clean intermediates and FASTQs ────────────────────────────────
echo "[$(date)] Step 4: cleaning intermediates"
for sample in "${samples[@]}"; do
    results_dir="$BATCH_ROOT/$sample/results/$sample"
    [[ -d "$results_dir" ]] || continue

    n_results=$(find "$results_dir" -name "*.txt" -path "*/arcashla/*" 2>/dev/null | wc -l)
    if [[ "$n_results" -eq 0 ]]; then
        echo "  WARNING: $sample has no arcashla result — keeping files for inspection"
        continue
    fi

    find "$results_dir/arcashla" -name "*.fq.gz"       -delete 2>/dev/null || true
    find "$results_dir/arcashla" -name "*.alignment.p" -delete 2>/dev/null || true
    [[ -d "$results_dir/t1k/t1k_out" ]] && \
        find "$results_dir/t1k/t1k_out" -name "*_candidate_*.fq" -delete 2>/dev/null || true
    [[ -d "$results_dir/t1k/t1k_out" ]] && \
        find "$results_dir/t1k/t1k_out" -name "*_aligned_*.fa"   -delete 2>/dev/null || true
    rm -f "$FASTQ_ROOT/${sample}_R1.fastq.gz" "$FASTQ_ROOT/${sample}_R2.fastq.gz"
    echo "  Cleaned $sample"
done

echo "[$(date)] Task ${SLURM_ARRAY_TASK_ID} complete. Disk:"
df -h /scratch/project_2008084/ | tail -1
