#!/bin/bash
# submit_rna_6trimodal.sh — RNA typing for the 6 Geuvadis+truth samples that
# need RNA to complete the 100-sample trimodal cohort.
#
# These samples have WGS done but need both WES and RNA. This script handles
# the RNA side; use slurm_wes_batch10.sh separately for WES.
# Both jobs should finish before running slurm_benchmark_trimodal.sh.
#
# Samples targeted (from find_trimodal_candidates.py output):
#   NA19153 NA19209 NA19210 NA20519 NA20521 NA20528
# Their FTP URLs are in sample_fastq_urls_batch5.tsv (auto-generated by
# find_trimodal_candidates.py).
#
# Usage: bash submit_rna_6trimodal.sh

set -euo pipefail

REPO=/scratch/project_2008084/pihla-publish
BATCH_DIR="$REPO/analysis/rna_6trimodal_batches"
BATCH5=/scratch/project_2008084/hla_calibration/rna/index/sample_fastq_urls_batch5.tsv

if [[ ! -f "$BATCH5" ]]; then
    echo "ERROR: $BATCH5 not found." >&2
    echo "       Run: python3 $REPO/bin/find_trimodal_candidates.py" >&2
    exit 1
fi

mkdir -p "$BATCH_DIR"

# ── 6 Geuvadis+truth samples needing RNA ─────────────────────────────────
RNA_6=(NA19153 NA19209 NA19210 NA20519 NA20521 NA20528)

# ── Single batch file (all 6 fit comfortably in one task) ────────────────
printf '%s\n' "${RNA_6[@]}" > "$BATCH_DIR/batch_0.txt"
echo "[$(date)] Batch file written: $BATCH_DIR/batch_0.txt (${#RNA_6[@]} samples)"

# ── Submit array job (single task) ───────────────────────────────────────
echo ""
echo "[$(date)] Submitting RNA array job (task 0)..."
ARRAY_JOB=$(sbatch --parsable \
    --array=0-0 \
    "$REPO/slurm_rna_array.sh" "$BATCH_DIR")
echo "  RNA array job: $ARRAY_JOB"

echo ""
echo "[$(date)] Done."
echo "  RNA job: $ARRAY_JOB"
echo ""
echo "After RNA and WES jobs finish, run the trimodal benchmark:"
echo "  sbatch --dependency=afterok:<WES_JOB>:${ARRAY_JOB} $REPO/slurm_benchmark_trimodal.sh"
echo ""
echo "Monitor:"
echo "  squeue -u ozcanumu -o '%.10i %.22j %.8T %.10M %R'"
